### ISSUE TITLE
Syntax error at alacritty.yml

### ISSUE THREAD

**Issue by rizzini** [ChristianChiarulli/Machfiles#12]
You need to uncomment the `#selection`.
```
selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true
  live_config_reload: true
```
